### ISSUE TITLE
Adopt alternative to timed polling for Spotify player status

### ISSUE THREAD

**Issue by alexpersian** [jonathangarelick/SoundSeer#14]
*please ignore if you've already explored these ideas*

There are a couple things from SpotMenu I saw after poking around that might help interfacing with the Spotify client more smoothly; specially around getting the player state.

Referencing the the Spotify app directly
* https://developer.apple.com/documentation/scriptingbridge/sbapplication
* https://github.com/kmikiy/SpotMenu/blob/master/MusicPlayer/Player/Spotify/Spotify.swift#L24

Using notification center for updates (push)
* https://developer.apple.com/documentation/foundation/distributednotificationcenter
* https://github.com/kmikiy/SpotMenu/blob/master/MusicPlayer/Global.swift#L14
* https://github.com/kmikiy/SpotMenu/tree/1a53424ea1802b88bf83db52f1044b65fb677642/MusicPlayer/Player/Spotify#L84

I think with this approach the AppleScript timed polling could be eliminated and even more performance would be found since it won't have to poll while the Spotify isn't active or playing.

**Comment by jonathangarelick** [comment]
This is excellent, I will definitely look into this.

**Comment by jonathangarelick** [comment]
A few tricky edge cases, but this is now working and merged into main. Thanks @alexpersian ! Hopefully will ship this with v1.1 sometime next week.

**Comment by alexpersian** [comment]
🔥🔥🔥
Excited to check it out!

**Comment by alexpersian** [comment]
Great stuff. Instant response now. 0 CPU usage while idle. 💯 

![image](https://github.com/jonathangarelick/SoundSeer/assets/5446451/7eec0495-b77c-462b-aa61-6259d3768921)

https://github.com/jonathangarelick/SoundSeer/assets/5446451/88bab04d-a981-4fbb-ab6f-e4c0eebf7996
